name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Setup Script
        run: |
         cd /home/ubuntu/actions-runner/_work/3tier-devops-task-manager/3tier-devops-task-manager

         chmod +x setup.sh
         ./setup.sh 
        

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
     
      #cleanup docker images and builder cache to free up space on self-hosted runner
      
      - name: Cleanup Docker
        run: |
          sudo docker system prune -af
          sudo docker builder prune -af
      # Build Frontend
      - name: Build Frontend Image
        run: |
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend

      # Build Backend
      - name: Build Backend Image
        run: |
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend

      # Push Frontend
      - name: Push Frontend Image
        run: |
          sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      # Push Backend
      - name: Push Backend Image
        run: |
          sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      # SSH Deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/actions-runner/_work/3tier-devops-task-manager/3tier-devops-task-manager

            sudo docker compose up -d --build 